name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Check out code
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Build executable
        run: go build -o freonit-app

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: freonit-app-executable
          path: freonit-app
